# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VetCare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VetCare
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'MBCalendarKit', '5.0.0'
  pod 'GoogleAPIClientForREST/Calendar', '~> 1.2.1'
  pod 'GoogleAPIClientForREST/Drive', '~> 1.2.1'
  pod 'GoogleSignIn', '~> 4.1.1'
  pod 'KontaktSDK', '~> 1.3'
  pod 'Charts'
  pod 'TPPDF'

end
